<a href="https://colab.research.google.com/github/juliocnsouzadev/notebooks/blob/issue-12-Tensors_with_Pytorch/PyTorch/Tensors_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

## Matrix multiplication
There are many important types of matrices which have their uses in neural networks. Some important matrices are matrices of ones (where each entry is set to 1) and the identity matrix (where the diagonal is set to 1 while all other values are 0). The identity matrix is very important in linear algebra: any matrix multiplied with identity matrix is simply the original matrix.

Let us experiment with these two types of matrices. You are going to build a matrix of ones with shape 3 by 3 called tensor_of_ones and an identity matrix of the same shape, called identity_tensor. We are going to see what happens when we multiply these two matrices, and what happens if we do an element-wise multiplication of them.

In [2]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.mm(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication =tensor_of_ones * identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Forward pass
Let's have something resembling more a neural network. The computational graph has been given below. You are going to initialize 3 large random tensors, and then do the operations as given in the computational graph. The final operation is the mean of the tensor, given by torch.mean(your_tensor).

In [3]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = x * y

# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(0.1249)


# Backpropagation using PyTorch

In [4]:
# Initialize x, y, and z to values 4, -3, and 5 with requires_grad=True to track computations
x = torch.tensor(4.0, requires_grad=True)
y = torch.tensor(-3.0, requires_grad=True)
z = torch.tensor(5.0, requires_grad=True)

# Set q to the sum of x and y, set f to the product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))


Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


In [5]:
# Multiply tensors x and y
q = torch.mul(x,y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

# The gradients are stored in the .grad attribute of tensors
print(f"Gradient of x: {x.grad}")
print(f"Gradient of y: {y.grad}")
print(f"Gradient of z: {z.grad}")

Gradient of x: -10.0
Gradient of y: 25.0
Gradient of z: -11.0


# Neural Network The Hard Way

In [6]:
input_layer = torch.rand(200,784)

# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([[21688.5996, 19725.2051, 20340.0273,  ..., 20458.7168, 20434.6289,
         19357.4355],
        [21582.0137, 19600.8398, 20221.3750,  ..., 20355.8828, 20316.5703,
         19281.7129],
        [21878.2949, 19862.1992, 20505.1797,  ..., 20641.1680, 20601.7441,
         19546.0977],
        ...,
        [21533.7148, 19542.9980, 20184.5098,  ..., 20321.6250, 20260.3652,
         19212.0879],
        [21323.2031, 19370.6074, 19989.3887,  ..., 20114.3027, 20076.8008,
         19025.1641],
        [21642.1289, 19671.7344, 20280.6895,  ..., 20424.2344, 20409.3887,
         19336.6133]])


In [7]:
# Neural Network - First with Pytorch

In [9]:
from torch import nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        # Instantiate all 2 linear layers
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):

        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return self.output(x)